name: jocaagura_domain
description: "A package with domain models for all transversal applications"
version: 1.14.0
homepage: https://github.com/jocaagura/jocaagura_domain

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

