name: Publish to pub.dev

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    environment: pub.dev

    # SOLO ejecutar si es merge desde develop o commit del bot
    if: |
      github.actor == 'github-actions[bot]' ||
      startsWith(github.event.head_commit.message, 'Merge branch \'develop\'') ||
      startsWith(github.event.head_commit.message, 'Bump version to')

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Validate Publication (Dry Run)
        run: flutter pub publish --dry-run || exit 1

      - name: Publish to pub.dev
        run: flutter pub publish --force
